version: '3.8'

services:
  backend:
    build: ./backend
    container_name: express_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend
