version: '3.8'

services:
  backend:
    build: ./backend
    container_name: express_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: database-test.cw6phqqltouz.us-east-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: MetaCode411#
      DB_NAME: user_management

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend
