version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crud_db
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: crud_db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
