version: '3.8'

services:
  backend:
    build: ./backend
    container_name: express_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
